# Generated by Django 4.1.6 on 2023-02-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bithday', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=3)),
                ('website', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=14)),
                ('city', models.CharField(max_length=5)),
                ('freelance', models.CharField(max_length=8)),
            ],
        ),
    ]
