# Generated by Django 4.1.6 on 2023-02-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infodetails',
            old_name='bithday',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='infodetails',
            name='freelance',
            field=models.CharField(max_length=9),
        ),
    ]
