# Generated by Django 4.1.6 on 2023-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0002_rename_bithday_infodetails_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=8)),
                ('degree_in', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=60)),
            ],
        ),
    ]
