# Generated by Django 4.1.6 on 2023-02-06 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='education',
            name='srt_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
