# Generated by Django 4.1.6 on 2023-02-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0005_alter_education_srt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='srt_date',
            new_name='start_date',
        ),
    ]
