# Generated by Django 4.1.6 on 2023-02-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0006_rename_srt_date_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_in',
            field=models.CharField(max_length=50),
        ),
    ]
