# Generated by Django 4.1.6 on 2023-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0007_alter_education_degree_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=30)),
                ('service_name', models.CharField(max_length=30)),
                ('service_details', models.CharField(max_length=500)),
            ],
        ),
    ]
