# Generated by Django 4.1.6 on 2023-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0008_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protfolio',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('images', models.ImageField(upload_to='images/project_img/')),
            ],
        ),
    ]
