# Generated by Django 4.1.6 on 2023-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0009_protfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protfolio',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/project_img/'),
        ),
    ]
