# Generated by Django 4.1.6 on 2023-02-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='AdminContact',
        ),
    ]
